services:

  primary:
    image: postgres:15-alpine
    container_name: ddb-postgres-primary
    ports:
      - "6666:5432"
    networks:
      - ddb-network
    volumes:
      - ddb-volume-primary:/data
      - ddb-volume-failover:/failover_dir
      - ./primary/postgresql.conf:/postgresql.conf
      - ./primary/fill_trash.sh:/fill_trash.sh
      - ./primary/remove_trash.sh:/remove_trash.sh
      - ./primary/start.sh:/start.sh
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: "md5\nhost replication all all md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    command: |
      postgres -c 'config_file=/postgresql.conf'

  standby:
    image: postgres:15-alpine
    container_name: ddb-postgres-standby
    ports:
      - "7777:5432"
    networks:
      - ddb-network
    volumes:
      - ddb-volume-standby:/data/postgres
      - ddb-volume-failover:/failover_dir
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGDATA: /data/postgres
    command: |
      bash -c "
      until pg_basebackup --pgdata=/data/postgres -R --slot=replication_slot -C --checkpoint=fast --host=standby --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      bash -c `echo -e \"promote_trigger_file = '/failover_dir/down.trg'\" >> /data/postgres/postgresql.conf`
      chown -Rf postgres:postgres /data/postgres
      chmod -R 700 /data/postgres
      su -p postgres -c postgres
      "
    depends_on:
      - primary

  balancer:
    image: pgpool/pgpool:4.4.3
    container_name: ddb-pgpool
    ports:
      - "9999:9999"
    networks:
      - ddb-network
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: password
    command: |
      bash -c "
      until pg_isready --dbname=postgres --host=postgres_primary --port=5432 --quiet --username=postgres && pg_isready --dbname=postgres --host=standby --port=5432 --quiet --username=postgres
      do
      echo 'Waiting for starting both nodes to connect...'
      sleep 1s
      done
      /opt/pgpool-II/bin/start.sh
      "
    volumes:
      - ddb-volume-failover:/failover_dir
      - ./balancer/pgpool.conf:/config/pgpool.conf
      - ./balancer/failover.sh:/failover.sh
    depends_on:
      - primary
      - standby

  filesystems:
    image: alpine
    container_name: ddb-filesystems
    command: tail -F anything
    volumes:
      - ddb-volume-primary:/primary
      - ddb-volume-standby:/replica
      - ddb-volume-failover:/failover

networks:
  ddb-network:
    driver: bridge

volumes:

  ddb-volume-primary:
    name: ddb-volume-primary
    driver: local
    driver_opts:
      o: "size=1g,uid=1000"
      device: tmpfs
      type: tmpfs

  ddb-volume-standby:
    name: ddb-volume-standby
    driver: local
    driver_opts:
      o: "size=1g,uid=1001"
      device: tmpfs
      type: tmpfs

  ddb-volume-failover:
    name: ddb-volume-failover
    driver: local
    driver_opts:
      o: "size=1m,uid=1002"
      device: tmpfs
      type: tmpfs
